

export type Song = {
  id?: number; // Optional: will be auto-generated by IndexedDB
  title: string;
  artist: string;
  fileUrl: string;
  characteristics: string[];
  file: File;
};

export type Playlist = {
  name: string;
  songs: Song[];
  type: 'manual' | 'ai';
};
